In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

---

# **Case Study: From Data to Diagnosis**
## *Handling Missing Values and Aggregating Patient Records Using Pandas*

---

### **Business Problem**
A hospital aims to enhance patient care and streamline operational efficiency through data-driven insights. To achieve this, they must analyze patient encounter data with the following objectives:

- **Identify trends** in hospital readmissions and associated costs
- **Filter and segment** patients by encounter type and payer information
- **Handle missing** or incomplete patient records effectively
- **Aggregate costs and stay durations** across different patient groups
- **Sort and merge** data to generate actionable insights for decision-making

In [3]:
import pandas as pd # Import the pandas library for data manipulation

# Read the 'encounters.csv' file into a pandas DataFrame
df_encounters = pd.read_csv('encounters.csv')

# Print a message indicating the display of the first few rows
print("First 5 rows of the dataset:")
# Display the first 5 rows of the DataFrame to get a quick overview of the data
df_encounters.head()

First 5 rows of the dataset:

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,NaN,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,NaN,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,NaN,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,NaN,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia

In [4]:
df_encounters.info() # Display a summary of the DataFrame including data types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27891 entries, 0 to 27890
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   27891 non-null  object
 1   START                27891 non-null  object
 2   STOP                 27891 non-null  object
 3   PATIENT              27891 non-null  object
 4   ORGANIZATION         27891 non-null  object
 5   PAYER                27891 non-null  object
 6   ENCOUNTERCLASS       27891 non-null  object
 7   CODE                 27891 non-null  int64
 8   DESCRIPTION          27891 non-null  object
 9   BASE_ENCOUNTER_COST  27891 non-null  float64
 10  TOTAL_CLAIM_COST     27891 non-null  float64
 11  PAYER_COVERAGE       27891 non-null  float64
 12  REASONCODE           8350 non-null   float64
 13  REASONDESCRIPTION    8350 non-null   object
dtypes: float64(4), int64(1), object(9)
memory usage: 3.0+ MB

# Column selection and Filtering the Data

In [5]:
#Columns of Interest
# Define a list of column names that are required for the analysis
required_cols=['Id','Patients','ENCOUNTERCLASS','BASE_ENCOUNTER_COST','PAYER','REASONDESCRIPTION']
# Create a new list with the lowercase versions of the required column names for consistency
#required_cols_lower=[i.lower() for i in required_cols]

In [6]:
print("Missing values in the dataframe")
df_encounters.isnull().sum() # Calculate and display the number of missing values in each column of the DataFrame

Missing values in the dataframe

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

In [7]:
df_encounters['BASE_ENCOUNTER_COST'].fillna(df_encounters['BASE_ENCOUNTER_COST'].median(), inplace=True)

/tmp/ipython-input-3523168780.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_encounters['BASE_ENCOUNTER_COST'].fillna(df_encounters['BASE_ENCOUNTER_COST'].median(), inplace=True)

In [8]:
 # Calculate the percentage of missing values in the 'REASONDESCRIPTION' column
 df_encounters['REASONDESCRIPTION'].isna().mean()*100

np.float64(70.06202717722563)

In [9]:
# Create a new DataFrame 'df_cleaned' by dropping rows where 'REASONDESCRIPTION' is missing.
# `subset=['REASONDESCRIPTION']` specifies that the `dropna` operation should only consider the 'REASONDESCRIPTION' column for missing values.
# `inplace=False` ensures that the original DataFrame (`df_encounters`) is not modified, and a new DataFrame (`df_cleaned`) is returned with the changes.
df_cleaned=df_encounters.dropna(subset=['REASONDESCRIPTION'], inplace=False)

In [10]:
df_cleaned.isna().sum()
# After dropping rows with missing 'REASONDESCRIPTION' values to create `df_cleaned`,
# the 'REASONCODE' column also shows 0 missing values. This suggests that
# 'REASONCODE' was missing in the same rows where 'REASONDESCRIPTION' was missing.

Id                     0
START                  0
STOP                   0
PATIENT                0
ORGANIZATION           0
PAYER                  0
ENCOUNTERCLASS         0
CODE                   0
DESCRIPTION            0
BASE_ENCOUNTER_COST    0
TOTAL_CLAIM_COST       0
PAYER_COVERAGE         0
REASONCODE             0
REASONDESCRIPTION      0
dtype: int64

In [11]:
# Average cost of BASE_ENCOUNTER_COST per ENCOUNTERCLASS
# This groups the 'df_cleaned' DataFrame by 'ENCOUNTERCLASS' and then calculates the mean of 'BASE_ENCOUNTER_COST' for each group.
avg_cost_per_class = df_cleaned.groupby('ENCOUNTERCLASS')['BASE_ENCOUNTER_COST'].mean()
print(avg_cost_per_class)

ENCOUNTERCLASS
ambulatory    110.034084
emergency     139.201323
inpatient     135.808129
outpatient     85.550000
wellness      136.800000
Name: BASE_ENCOUNTER_COST, dtype: float64

In [17]:
# Grouping TOTAL_CLAIM_COST by PAYER
TOTAL_CLAIM_COST_per_PAYER = df_cleaned.groupby('PAYER')['TOTAL_CLAIM_COST'].sum()
print("Total Payers:",len(TOTAL_CLAIM_COST_per_PAYER))
print(TOTAL_CLAIM_COST_per_PAYER)
#

Total Payers: 10
PAYER
047f6ec3-6215-35eb-9608-f9dda363a44c    1195513.62
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a    1700220.24
4d71f845-a6a9-3c39-b242-14d25ef86a8d    1091943.15
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf    1051841.75
6e2f1a2d-27bd-3701-8d08-dae202c58632    1623290.20
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a    7165889.64
7caa7254-5050-3b5e-9eae-bd5ea30e809c    2828182.83
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76    9983932.33
b3221cfc-24fb-339e-823d-bc4136cbc4ed     534523.99
d47b3510-2895-3b70-9897-342d681c769d    1354417.07
Name: TOTAL_CLAIM_COST, dtype: float64

In [18]:
# To get distinct rows of the DataFrame, use drop_duplicates().
# To get distinct values from a specific column, use df_cleaned['column_name'].unique()
# Let's see the shape of the DataFrame after dropping duplicate rows.
print(f"Original shape: {df_cleaned.shape}")
df_distinct_rows = df_cleaned.drop_duplicates(inplace=False)
print(f"Shape after dropping duplicates: {df_distinct_rows.shape}")
df_distinct_rows.head()

Original shape: (8350, 14)
Shape after dropping duplicates: (8350, 14)

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,d78e84ec-30aa-3bba-a33a-f29a3a454662,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,ambulatory,185347001,Encounter for problem,85.55,11855.19,11205.43,363406005.0,Malignant tumor of colon
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,9881.17,7872.94,254637007.0,Non-small cell lung cancer (disorder)
14,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07T21:02:09Z,2011-01-07T22:39:45Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185347001,Encounter for problem,85.55,5136.00,4076.80,424132000.0,Non-small cell carcinoma of lung TNM stage 1 ...
16,f39e72a6-a58e-0aea-cc1f-8aee6f126cc0,2011-01-08T15:20:55Z,2011-01-08T15:35:55Z,88986fec-6364-262e-37d4-e20ceb511166,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,390906007,Follow-up encounter,85.55,234.72,155.77,55822004.0,Hyperlipidemia

In [45]:
# # Sorting encounters by highest base cost
# df_sorted_by_base_cose=df_cleaned.sort_values(by='BASE_ENCOUNTER_COST', ascending=False)
# print("Top 5 Highest base cost encounters")
# df_sorted_by_base_cose[['Id','BASE_ENCOUNTER_COST']].head(5)

In [51]:
#df_cleaned.drop_duplicates(subset=['ENCOUNTERCLASS'], inplace=False)['ENCOUNTERCLASS'].value_counts()
df_cleaned['ENCOUNTERCLASS'].value_counts()

ENCOUNTERCLASS
ambulatory    7449
inpatient      513
emergency      310
wellness        51
outpatient      27
Name: count, dtype: int64

In [95]:
# Step 1: Filter all encounters where 'ENCOUNTERCLASS' is 'emergency'.
# .copy() is used to ensure we are working on a copy of the DataFrame slice
# to avoid SettingWithCopyWarning in future operations.
emergency_class = df_cleaned[df_cleaned['ENCOUNTERCLASS'] == 'emergency'].copy()
print(r'Missing values in ENCOUNTERCLASS:',emergency_class['ENCOUNTERCLASS'].isna().sum())
# Step 2: Calculate the mean of 'TOTAL_CLAIM_COST' specifically for emergency encounters.
# This mean will be used to fill any missing values in the 'TOTAL_CLAIM_COST' column
# within the emergency_class DataFrame.
mean_claim = emergency_class['TOTAL_CLAIM_COST'].mean()
print("Mean claim before imputing:",mean_claim)

# Step 3: Fill any missing values (NaN) in the 'TOTAL_CLAIM_COST' column of 'emergency_class'
# with the calculated mean claim cost. The .loc accessor is used for explicit indexing
# to prevent potential SettingWithCopyWarning.
emergency_class.loc[:, 'TOTAL_CLAIM_COST'] = emergency_class['TOTAL_CLAIM_COST'].fillna(mean_claim)

# Step 4: Recalculate the average 'TOTAL_CLAIM_COST' for emergency encounters
# after filling any missing values. This gives the final average claim cost.
avg_emergency_claim = emergency_class['TOTAL_CLAIM_COST'].mean()
print("Mean claim after imputing:",avg_emergency_claim)

if mean_claim==avg_emergency_claim:
  print("Mean claim before and after imputing are same, i.e. maybe there is no missing value")
else:
  print("Missing Value found")
# Step 5: Print the calculated average claim cost for emergency encounters.
# The f-string is used for formatted output.
# `:.2f` is a format specifier for floating-point numbers.
# It tells Python to format `avg_emergency_claim` as a float with exactly two digits
# after the decimal point, which is standard for monetary values.
print(f"AVG CLAIM COST FOR EMERGENCY ENCOUNTERS: {avg_emergency_claim:.2f}")

Missing values in ENCOUNTERCLASS: 0
Mean claim before imputing: 5193.448161290323
Mean claim after imputing: 5193.448161290323
Mean claim before and after imputing are same, i.e. maybe there is no missing value
AVG CLAIM COST FOR EMERGENCY ENCOUNTERS: 5193.45

### Explanation of `loc[:, 'TOTAL_CLAIM_COST']`

The syntax `loc[:, 'TOTAL_CLAIM_COST']` is a powerful way to select specific data from a Pandas DataFrame using label-based indexing. Let's break it down:

*   **`.loc`**: This is a Pandas accessor used for label-based indexing. It allows you to select rows and columns by their labels (names).

*   **`:` (before the comma)**: When used in the row selection part of `.loc` (before the comma), the colon `:` acts as a slice that means "select all rows" or "from the beginning to the end of the rows."

*   **`'TOTAL_CLAIM_COST'` (after the comma)**: This explicitly specifies the column label 'TOTAL_CLAIM_COST'. When placed after the comma, it instructs Pandas to select only this particular column.

**In summary, `emergency_class.loc[:, 'TOTAL_CLAIM_COST']` means:**
"From the `emergency_class` DataFrame, select **all rows** (`:`) and the column labeled **'TOTAL_CLAIM_COST'**."

This operation returns a Pandas Series containing all the values from the 'TOTAL_CLAIM_COST' column within the `emergency_class` DataFrame.